### ISSUE TITLE
Newsletter #6

### ISSUE THREAD

**Issue by Te-k** [securitywithoutborders/newsletter#17]
Some interesting article for newsletter 6:
* [Cyber encryption is out of sight for camera makers](https://www.ft.com/content/373fefea-2424-11e7-a34a-538b4cb30025)
* [Tainted Leaks: Disinformation and Phishing With a Russian Nexus](https://citizenlab.org/2017/05/tainted-leaks-disinformation-phish/)
* [Critical Samba vulnerability](https://lists.samba.org/archive/samba-announce/2017/000406.html)

**Comment by ajvb** [comment]
https://blog.qualys.com/securitylabs/2017/06/19/the-stack-clash
